/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRescueRouteImport } from './routes/_authenticated/rescue'
import { Route as AuthenticatedFishermanRouteImport } from './routes/_authenticated/fisherman'
import { Route as AuthenticatedBmuRouteImport } from './routes/_authenticated/bmu'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicIngestSosRouteImport } from './routes/api/public/ingest/sos'
import { Route as ApiPublicIngestLocationRouteImport } from './routes/api/public/ingest/location'
import { Route as ApiPublicIngestCancelRouteImport } from './routes/api/public/ingest/cancel'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRescueRoute = AuthenticatedRescueRouteImport.update({
  id: '/rescue',
  path: '/rescue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFishermanRoute = AuthenticatedFishermanRouteImport.update({
  id: '/fisherman',
  path: '/fisherman',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBmuRoute = AuthenticatedBmuRouteImport.update({
  id: '/bmu',
  path: '/bmu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicIngestSosRoute = ApiPublicIngestSosRouteImport.update({
  id: '/api/public/ingest/sos',
  path: '/api/public/ingest/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestLocationRoute = ApiPublicIngestLocationRouteImport.update({
  id: '/api/public/ingest/location',
  path: '/api/public/ingest/location',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestCancelRoute = ApiPublicIngestCancelRouteImport.update({
  id: '/api/public/ingest/cancel',
  path: '/api/public/ingest/cancel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bmu': typeof AuthenticatedBmuRoute
  '/fisherman': typeof AuthenticatedFishermanRoute
  '/rescue': typeof AuthenticatedRescueRoute
  '/api/public/ingest/cancel': typeof ApiPublicIngestCancelRoute
  '/api/public/ingest/location': typeof ApiPublicIngestLocationRoute
  '/api/public/ingest/sos': typeof ApiPublicIngestSosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/bmu': typeof AuthenticatedBmuRoute
  '/fisherman': typeof AuthenticatedFishermanRoute
  '/rescue': typeof AuthenticatedRescueRoute
  '/api/public/ingest/cancel': typeof ApiPublicIngestCancelRoute
  '/api/public/ingest/location': typeof ApiPublicIngestLocationRoute
  '/api/public/ingest/sos': typeof ApiPublicIngestSosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/bmu': typeof AuthenticatedBmuRoute
  '/_authenticated/fisherman': typeof AuthenticatedFishermanRoute
  '/_authenticated/rescue': typeof AuthenticatedRescueRoute
  '/api/public/ingest/cancel': typeof ApiPublicIngestCancelRoute
  '/api/public/ingest/location': typeof ApiPublicIngestLocationRoute
  '/api/public/ingest/sos': typeof ApiPublicIngestSosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/bmu'
    | '/fisherman'
    | '/rescue'
    | '/api/public/ingest/cancel'
    | '/api/public/ingest/location'
    | '/api/public/ingest/sos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/bmu'
    | '/fisherman'
    | '/rescue'
    | '/api/public/ingest/cancel'
    | '/api/public/ingest/location'
    | '/api/public/ingest/sos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/bmu'
    | '/_authenticated/fisherman'
    | '/_authenticated/rescue'
    | '/api/public/ingest/cancel'
    | '/api/public/ingest/location'
    | '/api/public/ingest/sos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicIngestCancelRoute: typeof ApiPublicIngestCancelRoute
  ApiPublicIngestLocationRoute: typeof ApiPublicIngestLocationRoute
  ApiPublicIngestSosRoute: typeof ApiPublicIngestSosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rescue': {
      id: '/_authenticated/rescue'
      path: '/rescue'
      fullPath: '/rescue'
      preLoaderRoute: typeof AuthenticatedRescueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fisherman': {
      id: '/_authenticated/fisherman'
      path: '/fisherman'
      fullPath: '/fisherman'
      preLoaderRoute: typeof AuthenticatedFishermanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bmu': {
      id: '/_authenticated/bmu'
      path: '/bmu'
      fullPath: '/bmu'
      preLoaderRoute: typeof AuthenticatedBmuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/ingest/sos': {
      id: '/api/public/ingest/sos'
      path: '/api/public/ingest/sos'
      fullPath: '/api/public/ingest/sos'
      preLoaderRoute: typeof ApiPublicIngestSosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/location': {
      id: '/api/public/ingest/location'
      path: '/api/public/ingest/location'
      fullPath: '/api/public/ingest/location'
      preLoaderRoute: typeof ApiPublicIngestLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest/cancel': {
      id: '/api/public/ingest/cancel'
      path: '/api/public/ingest/cancel'
      fullPath: '/api/public/ingest/cancel'
      preLoaderRoute: typeof ApiPublicIngestCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBmuRoute: typeof AuthenticatedBmuRoute
  AuthenticatedFishermanRoute: typeof AuthenticatedFishermanRoute
  AuthenticatedRescueRoute: typeof AuthenticatedRescueRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBmuRoute: AuthenticatedBmuRoute,
  AuthenticatedFishermanRoute: AuthenticatedFishermanRoute,
  AuthenticatedRescueRoute: AuthenticatedRescueRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicIngestCancelRoute: ApiPublicIngestCancelRoute,
  ApiPublicIngestLocationRoute: ApiPublicIngestLocationRoute,
  ApiPublicIngestSosRoute: ApiPublicIngestSosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
